'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
    Zap, Sparkles, Rocket, Globe, Shield,
    ArrowRight, MessageCircle, HelpCircle,
    ChevronDown, ChevronUp, Cpu, Users, Layers
} from 'lucide-react'
import { cn } from '@/lib/utils'

const faqs = [
    {
        question: "How does the AI generation actually work?",
        answer: "Our proprietary Prime Intelligence engine uses a multi-stage synthesis process. It first interprets your natural language vision into a high-level architecture JSON, which is then refined into specific frontend, backend, and database schemas. Finally, our code generation models compile this into production-ready React and Node.js code.",
        category: "Technology"
    },
    {
        question: "Can I export the code to my own servers?",
        answer: "Absolutely. We believe in zero vendor lock-in. You can export the full source code (TypeScript/Next.js/PostgreSQL) and deploy it to Vercel, AWS, or your own metal. The Architect plan even includes automated GitHub sync.",
        category: "Development"
    },
    {
        question: "What happens if the AI makes a mistake?",
        answer: "The AI provides the foundation and core logic. You can use our Visual Editor to manually refine any component or logic block. If a generation isn't perfect, you can provide corrective feedback to the AI in real-time to adjust the output.",
        category: "Support"
    },
    {
        question: "Is there a limit to how many users my apps can handle?",
        answer: "Apps generated by Prime Engine are built on scalable infrastructure by default. Depending on where you deploy, your app can handle anything from 100 to 1,000,000+ users. We provide the enterprise-grade blueprints; the sky is the limit.",
        category: "Scaling"
    },
]

export default function AboutPage() {
    const [openFaq, setOpenFaq] = useState<number | null>(0)

    return (
        <div className="min-h-screen py-24 px-6 relative overflow-hidden bg-dark-950">
            {/* Immersive Background */}
            <div className="absolute top-0 right-1/4 w-[600px] h-[600px] bg-primary-500/5 blur-[120px] pointer-events-none" />
            <div className="absolute bottom-0 left-1/4 w-[500px] h-[500px] bg-purple-500/5 blur-[100px] pointer-events-none" />

            <div className="max-w-7xl mx-auto relative z-10">
                {/* Brand Story Hero */}
                <section className="text-center mb-32 italic">
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="flex items-center justify-center gap-3 mb-6"
                    >
                        <div className="p-2 rounded-lg bg-primary-500/10 border border-primary-500/20">
                            <Zap className="w-5 h-5 text-primary-400 group-hover:rotate-12 transition-transform" />
                        </div>
                        <span className="text-xs font-black uppercase tracking-[0.2em] text-primary-400">The Prime Manifesto</span>
                    </motion.div>
                    <motion.h1
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1 }}
                        className="text-6xl md:text-8xl font-black text-white tracking-tight mb-10 leading-tight"
                    >
                        Democratizing <br />
                        <span className="gradient-text">Creation.</span>
                    </motion.h1>
                    <motion.p
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                        className="text-2xl text-dark-400 max-w-3xl mx-auto leading-relaxed font-medium"
                    >
                        We believe the barrier between an idea and a functioning application should be zero.
                        Prime Engine is our vision of a future where anyone, regardless of their technical background,
                        can architect complex systems using the power of natural language.
                    </motion.p>
                </section>

                {/* Values Grid */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-40">
                    {[
                        { icon: Cpu, title: "Silicon Precision", desc: "Our AI doesn't just guess; it architects. Every line of code is synthesized for performance and security." },
                        { icon: Users, title: "Human Centric", desc: "Technology should serve the creator. Our platform is designed to be as intuitive as a conversation." },
                        { icon: Layers, title: "Infinite Depth", desc: "From simple landing pages to complex enterprise SaaS, our engine adapts to your required complexity." },
                    ].map((value, i) => (
                        <motion.div
                            key={i}
                            initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                            transition={{ delay: i * 0.1 + 0.3 }}
                            className="glass p-10 rounded-[40px] border border-white/5 hover:border-primary-500/20 transition-all card-hover"
                        >
                            <div className="w-16 h-16 rounded-2xl bg-primary-500/10 flex items-center justify-center mb-8 shadow-2xl">
                                <value.icon className="w-8 h-8 text-primary-500" />
                            </div>
                            <h3 className="text-2xl font-black text-white mb-4 italic uppercase tracking-tight">{value.title}</h3>
                            <p className="text-dark-400 font-medium leading-relaxed">{value.desc}</p>
                        </motion.div>
                    ))}
                </div>

                {/* FAQ Center */}
                <section className="max-w-4xl mx-auto">
                    <div className="text-center mb-16 italic">
                        <span className="text-[10px] font-black uppercase tracking-[0.3em] text-dark-500">Support Hub</span>
                        <h2 className="text-4xl font-black text-white mt-4">Frequently Asked <span className="text-white/40">Questions</span></h2>
                    </div>

                    <div className="space-y-4">
                        {faqs.map((faq, i) => (
                            <motion.div
                                key={i}
                                className={cn(
                                    "rounded-3xl border transition-all duration-500 overflow-hidden",
                                    openFaq === i ? "bg-dark-900 border-primary-500/30 shadow-2xl shadow-primary-500/5" : "bg-dark-900/40 border-white/5 hover:border-white/10"
                                )}
                            >
                                <button
                                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                                    className="w-full flex items-center justify-between p-8 text-left group"
                                >
                                    <div className="flex items-center gap-6">
                                        <div className={cn(
                                            "w-10 h-10 rounded-xl flex items-center justify-center transition-colors",
                                            openFaq === i ? "bg-primary-500 text-white" : "bg-dark-800 text-dark-500 group-hover:text-white"
                                        )}>
                                            <HelpCircle className="w-5 h-5" />
                                        </div>
                                        <div>
                                            <span className="text-[10px] font-black uppercase tracking-widest text-primary-400 block mb-1">{faq.category}</span>
                                            <span className="text-lg font-black text-white tracking-tight">{faq.question}</span>
                                        </div>
                                    </div>
                                    {openFaq === i ? <ChevronUp className="w-6 h-6 text-primary-400" /> : <ChevronDown className="w-6 h-6 text-dark-500 group-hover:text-white" />}
                                </button>

                                <AnimatePresence>
                                    {openFaq === i && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: "auto", opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.3 }}
                                        >
                                            <div className="p-8 pt-0 border-t border-white/5">
                                                <p className="text-dark-400 font-medium leading-relaxed text-lg">
                                                    {faq.answer}
                                                </p>
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>
                        ))}
                    </div>

                    {/* Support Link */}
                    <div className="mt-20 glass p-10 rounded-[40px] border border-white/5 flex flex-col md:flex-row items-center justify-between gap-8 group hover:border-primary-500/40 transition-all">
                        <div className="flex items-center gap-6">
                            <div className="w-16 h-16 rounded-2xl bg-primary-500/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                                <MessageCircle className="w-8 h-8 text-primary-400" />
                            </div>
                            <div className="text-center md:text-left">
                                <h3 className="text-2xl font-black text-white italic">Still need coordinates?</h3>
                                <p className="text-dark-400 font-medium">Our architectural team is standing by to assist your build.</p>
                            </div>
                        </div>
                        <button className="btn-primary flex items-center gap-3 px-10 py-5 text-lg font-black whitespace-nowrap">
                            Contact Support
                            <ArrowRight className="w-5 h-5" />
                        </button>
                    </div>
                </section>
            </div>
        </div>
    )
}
