
import { Octokit } from "octokit";

// Simple ID generator if utils is missing
const generateId = () => Math.random().toString(36).substring(7);

const PROJECT_FILES = {
    "package.json": JSON.stringify({
        name: "my-ai-app",
        version: "0.1.0",
        private: true,
        scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
        },
        dependencies: {
            "react": "^18",
            "react-dom": "^18",
            "next": "14.1.0",
            "lucide-react": "latest",
            "framer-motion": "latest",
            "clsx": "latest",
            "tailwind-merge": "latest"
        },
        devDependencies: {
            "typescript": "^5",
            "@types/node": "^20",
            "@types/react": "^18",
            "@types/react-dom": "^18",
            "autoprefixer": "^10.0.1",
            "postcss": "^8",
            "tailwindcss": "^3.3.0"
        }
    }, null, 2),

    "next.config.js": `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;`,

    "tsconfig.json": JSON.stringify({
        compilerOptions: {
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [{ name: "next" }],
            paths: { "@/*": ["./src/*"] }
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"]
    }, null, 2),

    "tailwind.config.js": `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}`,

    "src/app/layout.tsx": `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Created with Prime Engine",
  description: "Generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`,
    "src/app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(to bottom, transparent, rgb(var(--background-end-rgb)))
    rgb(var(--background-start-rgb));
}
`
};

export async function deployToGitHub(githubToken: string, projectCode: string, projectName: string) {
    const octokit = new Octokit({ auth: githubToken });

    // 1. Get User Info
    const { data: user } = await octokit.rest.users.getAuthenticated();

    // 2. Create Repository
    const slug = generateId();
    const repoName = `${projectName.toLowerCase().replace(/\s+/g, '-')}-${slug}`;

    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        private: false,
        auto_init: true,
    });

    // 3. Create Files
    // Get latest commit SHA
    const { data: refData } = await octokit.rest.git.getRef({
        owner: user.login,
        repo: repoName,
        ref: "heads/main",
    });
    const latestCommitSha = refData.object.sha;

    const files: Record<string, string> = { ...PROJECT_FILES, "src/app/page.tsx": projectCode };

    const treeItems = [];
    for (const [path, content] of Object.entries(files)) {
        const { data: blob } = await octokit.rest.git.createBlob({
            owner: user.login,
            repo: repoName,
            content: content,
            encoding: "utf-8",
        });
        treeItems.push({
            path,
            mode: "100644" as const,
            type: "blob" as const,
            sha: blob.sha,
        });
    }

    // Create Tree
    const { data: tree } = await octokit.rest.git.createTree({
        owner: user.login,
        repo: repoName,
        base_tree: latestCommitSha,
        tree: treeItems,
    });

    // Create Commit
    const { data: newCommit } = await octokit.rest.git.createCommit({
        owner: user.login,
        repo: repoName,
        message: "Initial commit from Prime Engine AI",
        tree: tree.sha,
        parents: [latestCommitSha],
    });

    // Update Ref
    await octokit.rest.git.updateRef({
        owner: user.login,
        repo: repoName,
        ref: "heads/main",
        sha: newCommit.sha,
    });

    return {
        repoUrl: repo.html_url,
        deployUrl: `https://vercel.com/new/clone?repository-url=${encodeURIComponent(repo.html_url)}`
    };
}
