
import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { createRepoAndPush } from "@/lib/github";

export async function POST(req: Request) {
    const session = await auth();

    // @ts-ignore
    if (!session?.user?.githubAccessToken) {
        return NextResponse.json({ error: "GitHub account not connected" }, { status: 401 });
    }

    const { projectId, repoName } = await req.json();

    const project = await prisma.project.findUnique({
        where: { id: projectId },
        include: { pages: true, components: true }
    });

    if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 });

    // Prepare files for GitHub
    const files: { path: string; content: string }[] = [];

    // 1. Initial Next.js boilerplate (simplified for demo)
    files.push({
        path: "package.json",
        content: JSON.stringify({
            name: repoName,
            version: "0.1.0",
            private: false,
            scripts: { dev: "next dev", build: "next build", start: "next start" },
            dependencies: {
                "next": "14.1.0",
                "react": "^18",
                "react-dom": "^18",
                "lucide-react": "^0.300.0",
                "framer-motion": "^10.0.0",
                "clsx": "^2.0.0",
                "tailwind-merge": "^2.0.0"
            }
        }, null, 2)
    });

    files.push({
        path: "README.md",
        content: `# ${repoName}\n\nGenerated by Prime Engine AI.`
    });

    // 2. Add Component files
    project.components.forEach(comp => {
        files.push({
            path: `components/${comp.name}.tsx`,
            content: comp.code
        });
    });

    // 3. Add Page files
    project.pages.forEach(page => {
        // Basic routing handling for demo
        const path = page.route === '/' ? 'app/page.tsx' : `app/${page.route}/page.tsx`;
        files.push({
            path: path,
            content: page.code
        });
    });

    try {
        // @ts-ignore
        const repoUrl = await createRepoAndPush(session.user.githubAccessToken, repoName, files);

        // Vercel Deploy Link
        const vercelUrl = `https://vercel.com/new/clone?repository-url=${encodeURIComponent(repoUrl + ".git")}`;

        return NextResponse.json({ success: true, repoUrl, vercelUrl });
    } catch (err: any) {
        console.error("GitHub API Error:", err);
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}
